service: telegram-bot
runtime: python
env: flex
entrypoint: python -m main

runtime_config:
  python_version: 3.6

resources:
  cpu: 1
  memory_gb: 2.3
  disk_size_gb: 10
  volumes:
  - name: ramdisk1
    volume_type: tmpfs
    size_gb: 0.5

manual_scaling:
  instances: 1

health_check:
  enable_health_check: True
  check_interval_sec: 5
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2