resources:
  - type: storage.v1.bucket
    name: sls-fdl-telegram-bot-1-dev-1506685680641
  - type: cloudfunctions.v1beta2.function
    name: fdl-telegram-bot-1-dev-first
    properties:
      location: us-central1
      availableMemoryMb: 256
      timeout: 60s
      function: botHandler
      sourceArchiveUrl: >-
        gs://sls-fdl-telegram-bot-1-dev-1506685680641/serverless/fdl-telegram-bot-1/dev/1506691871410-2017-09-29T13:31:11.410Z/fdl-telegram-bot-1.zip
      httpsTrigger:
        url: path
