resources:
  - type: storage.v1.bucket
    name: sls-itt-telegram-prod-1507548425104
  - type: cloudfunctions.v1beta2.function
    name: itt-telegram-prod-bot
    properties:
      location: us-central1
      availableMemoryMb: 256
      timeout: 60s
      function: botHandler
      sourceArchiveUrl: >-
        gs://sls-itt-telegram-prod-1507548425104/serverless/itt-telegram/prod/1507560965449-2017-10-09T14:56:05.449Z/itt-telegram.zip
      httpsTrigger:
        url: path
